-- Ensure profiles table has is_present column
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_present boolean DEFAULT false;

-- Ensure occupancy_logs table exists
CREATE TABLE IF NOT EXISTS public.occupancy_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  action text not null check (action in ('check_in', 'check_out')),
  location text default 'main_gym',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for occupancy_logs if not already enabled
ALTER TABLE public.occupancy_logs ENABLE ROW LEVEL SECURITY;

-- Add RLS policies for occupancy_logs if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'occupancy_logs' AND policyname = 'Occupancy logs are viewable by everyone.'
    ) THEN
        CREATE POLICY "Occupancy logs are viewable by everyone." ON occupancy_logs FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'occupancy_logs' AND policyname = 'Users can insert own occupancy logs.'
    ) THEN
        CREATE POLICY "Users can insert own occupancy logs." ON occupancy_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
    END IF;
END
$$;

-- Function to handle user check-in and check-out
CREATE OR REPLACE FUNCTION public.handle_occupancy(action_type text, location_name text DEFAULT 'main_gym')
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_status boolean;
  result_message text;
BEGIN
  -- Validate action_type
  IF action_type NOT IN ('check_in', 'check_out') THEN
    RAISE EXCEPTION 'Invalid action type: %. Must be check_in or check_out.', action_type;
  END IF;

  -- Determine new status
  new_status := (action_type = 'check_in');

  -- Update profile status
  UPDATE public.profiles
  SET is_present = new_status
  WHERE id = auth.uid();

  -- Insert log
  INSERT INTO public.occupancy_logs (user_id, action, location)
  VALUES (auth.uid(), action_type, location_name);

  -- Initialize result message
  IF new_status THEN
    result_message := 'Successfully checked in!';
  ELSE
    result_message := 'Successfully checked out!';
  END IF;

  RETURN json_build_object(
    'success', true,
    'message', result_message,
    'is_present', new_status
  );
END;
$$;
