-- Create user_schedules table
create table public.user_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  day_of_week text not null, -- 'Monday', 'Tuesday', etc.
  period int not null, -- 1 to 10
  is_occupied boolean default true, -- true means class exists
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, day_of_week, period) -- Prevent duplicate entries for same slot
);

-- Enable RLS
alter table public.user_schedules enable row level security;

-- Policies
create policy "Users can view own schedule."
  on user_schedules for select
  using ( auth.uid() = user_id );

create policy "Users can insert own schedule."
  on user_schedules for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own schedule."
  on user_schedules for update
  using ( auth.uid() = user_id );

create policy "Users can delete own schedule."
  on user_schedules for delete
  using ( auth.uid() = user_id );
