-- 1. Update profiles table for Presence feature
alter table public.profiles 
add column if not exists is_present boolean default false;

-- 2. Create inquiries table
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  category text default 'General',
  message text not null,
  status text default 'Open', -- Open, In Progress, Resolved
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create equipment_logs table
create table if not exists public.equipment_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  equipment_name text not null,
  duration_seconds int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create friends table
create table if not exists public.friends (
  user_id uuid references public.profiles(id) not null,
  friend_id uuid references public.profiles(id) not null,
  status text check (status in ('pending', 'accepted', 'blocked')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, friend_id)
);

-- 5. Create groups table
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Create group_members table
create table if not exists public.group_members (
  group_id bigint references public.groups(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (group_id, user_id)
);

-- Enable RLS for all new tables
alter table public.inquiries enable row level security;
alter table public.equipment_logs enable row level security;
alter table public.friends enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;

-- Policies (Basic)

-- Inquiries: Users can insert own, view own
create policy "Users can insert own inquiries" on inquiries for insert with check (auth.uid() = user_id);
create policy "Users can view own inquiries" on inquiries for select using (auth.uid() = user_id);

-- Equipment Logs: Users can insert own, view own
create policy "Users can insert own equip logs" on equipment_logs for insert with check (auth.uid() = user_id);
create policy "Users can view own equip logs" on equipment_logs for select using (auth.uid() = user_id);

-- Friends: Users can view/insert their own friend relations
create policy "Users can view own friendships" on friends for select using (auth.uid() = user_id or auth.uid() = friend_id);
create policy "Users can insert friendships" on friends for insert with check (auth.uid() = user_id);
create policy "Users can update friendships" on friends for update using (auth.uid() = user_id or auth.uid() = friend_id);

-- Groups: Everyone can read groups (for search), Owner can update
create policy "Everyone can view groups" on groups for select using (true);
create policy "Auth users can create groups" on groups for insert with check (auth.role() = 'authenticated');
create policy "Owner can update group" on groups for update using (auth.uid() = owner_id);

-- Group Members: Members can view, Auth users can join
create policy "Everyone can view group members" on group_members for select using (true);
create policy "Users can join groups" on group_members for insert with check (auth.uid() = user_id);
