-- MASTER MIGRATION SCRIPT
-- This script sets up the entire database schema for the Training Heros app.
-- Run this in the Supabase SQL Editor for your new project.

-- ==========================================
-- 1. Base Schema (supabase_schema.sql)
-- ==========================================

-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  student_id text,
  avatar_stats jsonb default '{"chest": 1, "arms": 1, "legs": 1, "abs": 1}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create workout_logs table
create table public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  muscle_part text not null,
  exercise_name text,
  reps int,
  weight float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for workout_logs
alter table public.workout_logs enable row level security;

create policy "Users can view own workout logs."
  on workout_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert own workout logs."
  on workout_logs for insert
  with check ( auth.uid() = user_id );

-- Create occupancy_logs table
create table public.occupancy_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  action text not null check (action in ('check_in', 'check_out')),
  location text default 'main_gym',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for occupancy_logs
alter table public.occupancy_logs enable row level security;

create policy "Occupancy logs are viewable by everyone."
  on occupancy_logs for select
  using ( true );

create policy "Users can insert own occupancy logs."
  on occupancy_logs for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup (Standard version, will be updated later)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ==========================================
-- 2. Advanced Features (create_advanced_features.sql)
-- ==========================================

-- Update profiles table for Presence feature
alter table public.profiles 
add column if not exists is_present boolean default false;

-- Create inquiries table
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  category text default 'General',
  message text not null,
  status text default 'Open',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create equipment_logs table
create table if not exists public.equipment_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  equipment_name text not null,
  duration_seconds int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create friends table
create table if not exists public.friends (
  user_id uuid references public.profiles(id) not null,
  friend_id uuid references public.profiles(id) not null,
  status text check (status in ('pending', 'accepted', 'blocked')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, friend_id)
);

-- Create groups table
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create group_members table
create table if not exists public.group_members (
  group_id bigint references public.groups(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (group_id, user_id)
);

-- Enable RLS for all new tables
alter table public.inquiries enable row level security;
alter table public.equipment_logs enable row level security;
alter table public.friends enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;

-- Policies (Basic)
create policy "Users can insert own inquiries" on inquiries for insert with check (auth.uid() = user_id);
create policy "Users can view own inquiries" on inquiries for select using (auth.uid() = user_id);

create policy "Users can insert own equip logs" on equipment_logs for insert with check (auth.uid() = user_id);
create policy "Users can view own equip logs" on equipment_logs for select using (auth.uid() = user_id);

create policy "Users can view own friendships" on friends for select using (auth.uid() = user_id or auth.uid() = friend_id);
create policy "Users can insert friendships" on friends for insert with check (auth.uid() = user_id);
create policy "Users can update friendships" on friends for update using (auth.uid() = user_id or auth.uid() = friend_id);

create policy "Everyone can view groups" on groups for select using (true);
create policy "Auth users can create groups" on groups for insert with check (auth.role() = 'authenticated');
create policy "Owner can update group" on groups for update using (auth.uid() = owner_id);

create policy "Everyone can view group members" on group_members for select using (true);
create policy "Users can join groups" on group_members for insert with check (auth.uid() = user_id);


-- ==========================================
-- 3. Schedule Table (create_schedule_table.sql)
-- ==========================================

create table public.user_schedules (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  day_of_week text not null,
  period int not null,
  is_occupied boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, day_of_week, period)
);

alter table public.user_schedules enable row level security;

create policy "Users can view own schedule." on user_schedules for select using ( auth.uid() = user_id );
create policy "Users can insert own schedule." on user_schedules for insert with check ( auth.uid() = user_id );
create policy "Users can update own schedule." on user_schedules for update using ( auth.uid() = user_id );
create policy "Users can delete own schedule." on user_schedules for delete using ( auth.uid() = user_id );


-- ==========================================
-- 4. Additional Columns (Consolidated)
-- ==========================================

-- Available Hours (from add_onboarding_columns.sql)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS available_hours JSONB;

-- Body Stats (from add_body_stats_columns.sql)
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS height numeric,
ADD COLUMN IF NOT EXISTS weight numeric,
ADD COLUMN IF NOT EXISTS body_fat numeric DEFAULT 15.0,
ADD COLUMN IF NOT EXISTS last_workout_at timestamptz DEFAULT now();

-- Equipment Log Details (from add_equipment_log_details.sql)
ALTER TABLE public.equipment_logs
ADD COLUMN IF NOT EXISTS weight numeric,
ADD COLUMN IF NOT EXISTS reps integer;

-- Fitness Goal (from add_goal_column.sql)
alter table public.profiles 
add column if not exists fitness_goal text default 'General Fitness';

-- Display Name (from update_schema.sql)
alter table public.profiles 
add column if not exists display_name text;


-- ==========================================
-- 5. Data Integrity (enable_delete_user.sql)
-- ==========================================

-- Add CASCADE delete to Foreign Keys to allow user deletion
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.user_schedules DROP CONSTRAINT IF EXISTS user_schedules_user_id_fkey;
ALTER TABLE public.user_schedules ADD CONSTRAINT user_schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.equipment_logs DROP CONSTRAINT IF EXISTS equipment_logs_user_id_fkey;
ALTER TABLE public.equipment_logs ADD CONSTRAINT equipment_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.occupancy_logs DROP CONSTRAINT IF EXISTS occupancy_logs_user_id_fkey;
ALTER TABLE public.occupancy_logs ADD CONSTRAINT occupancy_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- ==========================================
-- 6. Student ID Enforcements (add_unique_student_id.sql, make_student_id_immutable.sql)
-- ==========================================

-- Add UNIQUE constraint
ALTER TABLE public.profiles
ADD CONSTRAINT unique_student_id UNIQUE (student_id);

-- Update Trigger to populate student_id from User Metadata
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, student_id)
  VALUES (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'student_id'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Add Trigger to Prevent Student ID Changes (Immutability)
CREATE OR REPLACE FUNCTION public.prevent_student_id_change()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.student_id IS DISTINCT FROM OLD.student_id THEN
    NEW.student_id := OLD.student_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ensure_student_id_immutable
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE PROCEDURE public.prevent_student_id_change();
