-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  student_id text,
  avatar_stats jsonb default '{"chest": 1, "arms": 1, "legs": 1, "abs": 1}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create workout_logs table
create table public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  muscle_part text not null,
  exercise_name text,
  reps int,
  weight float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for workout_logs
alter table public.workout_logs enable row level security;

create policy "Users can view own workout logs."
  on workout_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert own workout logs."
  on workout_logs for insert
  with check ( auth.uid() = user_id );

-- Create occupancy_logs table
create table public.occupancy_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  action text not null check (action in ('check_in', 'check_out')),
  location text default 'main_gym',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for occupancy_logs
alter table public.occupancy_logs enable row level security;

create policy "Occupancy logs are viewable by everyone."
  on occupancy_logs for select
  using ( true );

create policy "Users can insert own occupancy logs."
  on occupancy_logs for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
